Insert Into COUNTRY_MASTER Values(1,'+91','India');
Insert Into COUNTRY_MASTER Values(2,'+61','Australia');
Insert Into STATES_MASTER Values(1,1,'Andhra Pradesh');
Insert Into STATES_MASTER Values(2,1,'Telangana');
Insert Into STATES_MASTER Values(3,2,'Victoria');
Insert Into STATES_MASTER Values(4,2,'WA');
insert into STATES_MASTER values(5,2,'NSW');
Insert Into CITIES_MASTER Values(1,'Vizag',1);
Insert Into CITIES_MASTER Values(2,'Guntur',1);
Insert Into CITIES_MASTER Values(3,'Hyderabad',2);
Insert Into CITIES_MASTER Values(4,'Adilabad',2);
Insert Into CITIES_MASTER Values(11,'Karimnagar',2);
Insert Into CITIES_MASTER Values(5,'Melbourne',3);
Insert Into CITIES_MASTER Values(6,'Geelong',3);
Insert Into CITIES_MASTER Values(7,'Sydney',5);
Insert Into CITIES_MASTER Values(8,'Mennienge',5);
Insert Into CITIES_MASTER Values(9,'Adelide',4);
Insert Into CITIES_MASTER Values(10,'Perth',4);